/**
 * DerivationMap — English Word-Family Relationships
 * 
 * A static map of ~150 common English word-family derivations.
 * When the generator encounters a derivative word (e.g., "kingdom"),
 * it looks up the root ("king") and applies a derivational affix
 * instead of generating a completely unrelated word.
 * 
 * This creates etymological coherence — the single most noticeable
 * quality of a "real-feeling" constructed language.
 */

import type { DerivationType } from './LanguageGrammarConfig';

export interface DerivationEntry {
  root: string;
  type: DerivationType;
}

export const DERIVATION_MAP: Record<string, DerivationEntry> = {
  // ── Place / Domain ────────────────────────────────────────────────
  'kingdom':    { root: 'king',    type: 'place' },
  'queendom':   { root: 'queen',   type: 'place' },
  'homeland':   { root: 'home',    type: 'place' },
  'woodland':   { root: 'wood',    type: 'place' },
  'farmland':   { root: 'farm',    type: 'place' },
  'wasteland':  { root: 'waste',   type: 'place' },
  'marshland':  { root: 'marsh',   type: 'place' },
  'borderland': { root: 'border',  type: 'place' },
  'heartland':  { root: 'heart',   type: 'place' },
  'mainland':   { root: 'main',    type: 'place' },
  'lowland':    { root: 'low',     type: 'place' },
  'highland':   { root: 'high',    type: 'place' },
  'grassland':  { root: 'grass',   type: 'place' },
  'northland':  { root: 'north',   type: 'place' },
  'southland':  { root: 'south',   type: 'place' },
  'eastland':   { root: 'east',    type: 'place' },
  'westland':   { root: 'west',    type: 'place' },
  'motherland': { root: 'mother',  type: 'place' },
  'fatherland': { root: 'father',  type: 'place' },
  'shadowland': { root: 'shadow',  type: 'place' },
  'dreamland':  { root: 'dream',   type: 'place' },
  'darkland':   { root: 'dark',    type: 'place' },
  'graveyard':  { root: 'grave',   type: 'place' },
  'churchyard': { root: 'church',  type: 'place' },
  'courtyard':  { root: 'court',   type: 'place' },
  'shipyard':   { root: 'ship',    type: 'place' },
  'armory':     { root: 'arm',     type: 'place' },
  'treasury':   { root: 'treasure',type: 'place' },
  'sanctuary':  { root: 'saint',   type: 'place' },
  'cemetery':   { root: 'dead',    type: 'place' },

  // ── Agent ─────────────────────────────────────────────────────────
  'fighter':    { root: 'fight',    type: 'agent' },
  'hunter':     { root: 'hunt',     type: 'agent' },
  'warrior':    { root: 'war',      type: 'agent' },
  'healer':     { root: 'heal',     type: 'agent' },
  'ruler':      { root: 'rule',     type: 'agent' },
  'builder':    { root: 'build',    type: 'agent' },
  'keeper':     { root: 'keep',     type: 'agent' },
  'speaker':    { root: 'speak',    type: 'agent' },
  'rider':      { root: 'ride',     type: 'agent' },
  'singer':     { root: 'sing',     type: 'agent' },
  'dancer':     { root: 'dance',    type: 'agent' },
  'worker':     { root: 'work',     type: 'agent' },
  'leader':     { root: 'lead',     type: 'agent' },
  'teacher':    { root: 'teach',    type: 'agent' },
  'watcher':    { root: 'watch',    type: 'agent' },
  'seeker':     { root: 'seek',     type: 'agent' },
  'breaker':    { root: 'break',    type: 'agent' },
  'maker':      { root: 'make',     type: 'agent' },
  'thinker':    { root: 'think',    type: 'agent' },
  'swimmer':    { root: 'swim',     type: 'agent' },
  'climber':    { root: 'climb',    type: 'agent' },
  'runner':     { root: 'run',      type: 'agent' },
  'walker':     { root: 'walk',     type: 'agent' },
  'wanderer':   { root: 'wander',   type: 'agent' },
  'defender':   { root: 'defend',   type: 'agent' },
  'attacker':   { root: 'attack',   type: 'agent' },
  'conqueror':  { root: 'conquer',  type: 'agent' },
  'destroyer':  { root: 'destroy',  type: 'agent' },
  'creator':    { root: 'create',   type: 'agent' },
  'protector':  { root: 'protect',  type: 'agent' },
  'follower':   { root: 'follow',   type: 'agent' },
  'believer':   { root: 'believe',  type: 'agent' },
  'dreamer':    { root: 'dream',    type: 'agent' },
  'trader':     { root: 'trade',    type: 'agent' },
  'player':     { root: 'play',     type: 'agent' },
  'killer':     { root: 'kill',     type: 'agent' },
  'sailor':     { root: 'sail',     type: 'agent' },
  'shepherd':   { root: 'sheep',    type: 'agent' },
  'sorcerer':   { root: 'sorcery',  type: 'agent' },

  // ── Adjective ─────────────────────────────────────────────────────
  'kingly':     { root: 'king',     type: 'adjective' },
  'queenly':    { root: 'queen',    type: 'adjective' },
  'godly':      { root: 'god',      type: 'adjective' },
  'ghostly':    { root: 'ghost',    type: 'adjective' },
  'deadly':     { root: 'dead',     type: 'adjective' },
  'lordly':     { root: 'lord',     type: 'adjective' },
  'priestly':   { root: 'priest',   type: 'adjective' },
  'beastly':    { root: 'beast',    type: 'adjective' },
  'saintly':    { root: 'saint',    type: 'adjective' },
  'brotherly':  { root: 'brother',  type: 'adjective' },
  'sisterly':   { root: 'sister',   type: 'adjective' },
  'motherly':   { root: 'mother',   type: 'adjective' },
  'fatherly':   { root: 'father',   type: 'adjective' },
  'cowardly':   { root: 'coward',   type: 'adjective' },
  'powerful':   { root: 'power',    type: 'adjective' },
  'fearful':    { root: 'fear',     type: 'adjective' },
  'beautiful':  { root: 'beauty',   type: 'adjective' },
  'hopeful':    { root: 'hope',     type: 'adjective' },
  'wrathful':   { root: 'wrath',    type: 'adjective' },
  'peaceful':   { root: 'peace',    type: 'adjective' },
  'truthful':   { root: 'truth',    type: 'adjective' },
  'faithful':   { root: 'faith',    type: 'adjective' },
  'watchful':   { root: 'watch',    type: 'adjective' },
  'sorrowful':  { root: 'sorrow',   type: 'adjective' },
  'dreadful':   { root: 'dread',    type: 'adjective' },
  'merciful':   { root: 'mercy',    type: 'adjective' },
  'joyful':     { root: 'joy',      type: 'adjective' },
  'woeful':     { root: 'woe',      type: 'adjective' },
  'graceful':   { root: 'grace',    type: 'adjective' },
  'hateful':    { root: 'hate',     type: 'adjective' },
  'vengeful':   { root: 'vengeance',type: 'adjective' },

  // ── Abstract Noun ─────────────────────────────────────────────────
  'freedom':    { root: 'free',     type: 'abstractNoun' },
  'wisdom':     { root: 'wise',     type: 'abstractNoun' },
  'darkness':   { root: 'dark',     type: 'abstractNoun' },
  'kindness':   { root: 'kind',     type: 'abstractNoun' },
  'strength':   { root: 'strong',   type: 'abstractNoun' },
  'weakness':   { root: 'weak',     type: 'abstractNoun' },
  'madness':    { root: 'mad',      type: 'abstractNoun' },
  'sadness':    { root: 'sad',      type: 'abstractNoun' },
  'happiness':  { root: 'happy',    type: 'abstractNoun' },
  'bravery':    { root: 'brave',    type: 'abstractNoun' },
  'slavery':    { root: 'slave',    type: 'abstractNoun' },
  'mastery':    { root: 'master',   type: 'abstractNoun' },
  'treachery':  { root: 'traitor',  type: 'abstractNoun' },
  'chivalry':   { root: 'knight',   type: 'abstractNoun' },
  'villainy':   { root: 'villain',  type: 'abstractNoun' },
  'tyranny':    { root: 'tyrant',   type: 'abstractNoun' },
  'prophecy':   { root: 'prophet',  type: 'abstractNoun' },
  'loyalty':    { root: 'loyal',    type: 'abstractNoun' },
  'cruelty':    { root: 'cruel',    type: 'abstractNoun' },
  'majesty':    { root: 'king',     type: 'abstractNoun' },
  'nobility':   { root: 'noble',    type: 'abstractNoun' },
  'divinity':   { root: 'divine',   type: 'abstractNoun' },
  'mortality':  { root: 'mortal',   type: 'abstractNoun' },
  'immortality':{ root: 'immortal', type: 'abstractNoun' },
  'eternity':   { root: 'eternal',  type: 'abstractNoun' },
  'glory':      { root: 'glory',    type: 'abstractNoun' },
  'honor':      { root: 'honor',    type: 'abstractNoun' },
  'valor':      { root: 'brave',    type: 'abstractNoun' },
  'fury':       { root: 'furious',  type: 'abstractNoun' },
  'agony':      { root: 'pain',     type: 'abstractNoun' },
  'sorcery':    { root: 'magic',    type: 'abstractNoun' },
  'witchcraft': { root: 'witch',    type: 'abstractNoun' },
  'enmity':     { root: 'enemy',    type: 'abstractNoun' },
  'piety':      { root: 'pious',    type: 'abstractNoun' },

  // ── Diminutive ────────────────────────────────────────────────────
  'dagger':     { root: 'sword',    type: 'diminutive' },
  'pony':       { root: 'horse',    type: 'diminutive' },
  'cottage':    { root: 'house',    type: 'diminutive' },
  'brook':      { root: 'river',    type: 'diminutive' },
  'hillock':    { root: 'hill',     type: 'diminutive' },
  'hamlet':     { root: 'town',     type: 'diminutive' },
  'sapling':    { root: 'tree',     type: 'diminutive' },
  'spark':      { root: 'flame',    type: 'diminutive' },
  'pebble':     { root: 'stone',    type: 'diminutive' },
  'pond':       { root: 'lake',     type: 'diminutive' },
  'cub':        { root: 'bear',     type: 'diminutive' },
  'colt':       { root: 'horse',    type: 'diminutive' },
  'creek':      { root: 'river',    type: 'diminutive' },
  'isle':       { root: 'island',   type: 'diminutive' },
  'hatchet':    { root: 'axe',      type: 'diminutive' },

  // ── Augmentative ──────────────────────────────────────────────────
  'mountain':   { root: 'hill',     type: 'augmentative' },
  'fortress':   { root: 'fort',     type: 'augmentative' },
  'palace':     { root: 'house',    type: 'augmentative' },
  'ocean':      { root: 'sea',      type: 'augmentative' },
  'cathedral':  { root: 'temple',   type: 'augmentative' },
  'inferno':    { root: 'fire',     type: 'augmentative' },
  'tempest':    { root: 'storm',    type: 'augmentative' },
  'citadel':    { root: 'castle',   type: 'augmentative' },
  'empire':     { root: 'kingdom',  type: 'augmentative' },
  'legion':     { root: 'army',     type: 'augmentative' },
  'colossus':   { root: 'statue',   type: 'augmentative' },
  'titan':      { root: 'giant',    type: 'augmentative' },
  'behemoth':   { root: 'beast',    type: 'augmentative' },
  'leviathan':  { root: 'serpent',  type: 'augmentative' },
  'maelstrom':  { root: 'whirlpool',type: 'augmentative' },
};
